name: Bug Report
description: Send a bug report
title: "[Bug]: "
labels: ["type | bug", "tag | triage"]
assignees:
  - shiipou
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report!
  - type: textarea
    id: what-happened
    attributes:
      label: What happened?
      description: Also tell us, what did you expect to happen?
      placeholder: Tell us what you see!
      value: "A bug happened!"
    validations:
      required: true
  - type: dropdown
    id: os
    attributes:
      label: On what OS are you seeing the problem on?
      multiple: true
      options:
        - Windows
        - Linux
        - Mac OS
        - Android
        - iOS
  - type: dropdown
    id: app_type
    attributes:
      label: What type of app did you use when the problem occure ?
      multiple: true
      options:
        - Native
        - Web Firefox
        - Web Chrome (or chrome-based)
        - Web Safari
        - Web Microsoft Edge
        - Other (specify above)
  - type: input
    id: version
    attributes:
      label: Version
      description: What version of the app are you running?
    validations:
      required: false
  - type: textarea
    id: logs
    attributes:
      label: Relevant log output
      description: Please copy and paste any relevant log output. This will be automatically formatted into code, so no need for backticks.
      render: Shell
  # - type: checkboxes
  #   id: terms
  #   attributes:
  #     label: Code of Conduct
  #     description: By submitting this issue, you agree to follow our [Code of Conduct](https://example.com)
  #     options:
  #       - label: I agree to follow this project's Code of Conduct
  #         required: true
